/**
 * The public catalogue's own copy, shared by the list and by Course Details.
 *
 * It lives beside the two screens rather than in the global dictionary because every entry here is
 * catalogue vocabulary, and because both screens must render the same words for the same thing —
 * two copies of "Course outline" is how the list and the detail page start disagreeing.
 */
export const catalogueCopy = {
  ar: {
    catalogue: "الكتالوج",
    loading: "جارٍ تحميل الدورات…",
    empty: "لا توجد دورات منشورة الآن.",
    unavailable: "هذه الدورة غير متاحة.",
    failed: "تعذر تحميل الكتالوج. حاول مرة أخرى.",
    instructor: "المدرب",
    outline: "محتوى الدورة",
    lessons: "دروس",
    price: "السعر الإرشادي",
    preview: "تتوفر معاينة عامة",
    navigation: "التنقل الرئيسي",
    skip: "انتقل إلى المحتوى",
    switchLanguage: "التبديل إلى الإنجليزية",
    searchLabel: "ابحث في الكتالوج",
    searchPlaceholder: "ابحث باسم الدورة أو وصفها",
    searchSubmit: "بحث",
    searching: "جارٍ البحث في الدورات…",
    noResults: "لا توجد دورات مطابقة.",
    watchPreview: "شاهد المعاينة",
    previewHeading: "معاينة: ",
    previewFailed: "تعذّر تشغيل المعاينة. حاول مرة أخرى.",
    clearSearch: "مسح البحث",
    retry: "إعادة المحاولة",
    clearFilters: "مسح التصفية",
    audience: "مناسب لتخصصات",
    emptyForInstitution: "لا توجد دورات منشورة لهذه الجامعة بعد.",
    emptyForProgram: "لا توجد دورات منشورة لهذا التخصص بعد.",
    emptyForLevel: "لا توجد دورات منشورة لهذا المستوى بعد.",
    emptyForSubject: "لا توجد دورات منشورة لهذا المقرر بعد.",
    relevanceNote: "الدورات المناسبة لتخصصك تظهر أولاً.",
  },
  en: {
    catalogue: "Catalogue",
    loading: "Loading courses…",
    empty: "No published courses are available yet.",
    unavailable: "This course is unavailable.",
    failed: "The catalogue could not be loaded. Try again.",
    instructor: "Instructor",
    outline: "Course outline",
    lessons: "lessons",
    price: "Price guidance",
    preview: "Public preview available",
    navigation: "Primary navigation",
    skip: "Skip to content",
    switchLanguage: "Switch to Arabic",
    searchLabel: "Search the catalogue",
    searchPlaceholder: "Search course titles or descriptions",
    searchSubmit: "Search",
    searching: "Searching courses…",
    noResults: "No matching courses were found.",
    watchPreview: "Watch preview",
    previewHeading: "Preview: ",
    previewFailed: "The preview could not be played. Try again.",
    clearSearch: "Clear search",
    retry: "Retry",
    clearFilters: "Clear filters",
    audience: "Relevant to",
    emptyForInstitution: "No published courses for this university yet.",
    emptyForProgram: "No published courses for this program yet.",
    emptyForLevel: "No published courses for this academic level yet.",
    emptyForSubject: "No published courses for this subject yet.",
    relevanceNote: "Courses relevant to your program appear first.",
  },
};
